# =============================================================================
# Multi-stage Dockerfile generated by AI Agent
#   Stage 1: build the React client into static assets
#   Stage 2: install production server dependencies
#   Stage 3: runtime image with the server + built client only
#
# The server reads PORT from the environment and binds to 0.0.0.0, so the
# same image runs unchanged on a host or in the container.
# =============================================================================

# --- Stage 1: client build ---------------------------------------------------
FROM node:20-bookworm-slim AS client-build
WORKDIR /app/client
COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client/ ./
RUN npm run build

# --- Stage 2: server production dependencies ---------------------------------
FROM node:20-bookworm-slim AS server-deps
WORKDIR /app/server
COPY server/package.json server/package-lock.json ./
RUN npm ci --omit=dev

# --- Stage 3: runtime ---------------------------------------------------------
FROM node:20-bookworm-slim
ENV NODE_ENV=production
WORKDIR /app

COPY --from=server-deps /app/server/node_modules ./server/node_modules
COPY server/package.json ./server/
COPY server/src ./server/src
COPY --from=client-build /app/client/dist ./client/dist

EXPOSE 3000

CMD ["node", "server/src/index.js"]
