import { Router } from 'express';
import { getEventType } from '../event-types.js';
import { dateInWindow, fitsBusinessHours, parseSlotId } from '../slots.js';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Logic generated by AI Agent: booking creation guarded by a transaction. The
// overlap check (`start_time < newEnd AND end_time > newStart`) plus a
// UNIQUE(start_time) backstop enforce the global occupancy rule across event
// types; a violation is surfaced as HTTP 409 with the contract error message.
export function bookingsRouter(db) {
  const router = Router();

  router.post('/', (req, res) => {
    const { eventTypeId, slotId, name, email } = req.body ?? {};

    const typeId = typeof eventTypeId === 'number' ? String(eventTypeId) : eventTypeId;
    if (typeof typeId !== 'string' || !/^\d+$/.test(typeId)) {
      return res.status(400).json({ error: 'eventTypeId is required and must be a numeric id.' });
    }

    const eventType = getEventType(db, typeId);
    if (!eventType) {
      return res.status(404).json({ error: 'Event type not found.' });
    }

    const parsed = parseSlotId(slotId);
    if (!parsed) {
      return res.status(400).json({ error: 'slotId is missing or malformed.' });
    }
    if (!dateInWindow(parsed.date)) {
      return res.status(400).json({ error: 'This slot is outside the 14-day booking window.' });
    }
    if (!fitsBusinessHours(eventType, slotId)) {
      return res.status(404).json({ error: 'The requested slot does not exist.' });
    }

    if (typeof name !== 'string' || name.trim().length === 0) {
      return res.status(400).json({ error: 'name is required and must not be empty.' });
    }
    const cleanName = name.trim();

    let cleanEmail = null;
    if (email !== undefined && email !== null && email !== '') {
      if (typeof email !== 'string' || !EMAIL_RE.test(email.trim())) {
        return res.status(400).json({ error: 'email must be a valid email address.' });
      }
      cleanEmail = email.trim().toLowerCase();
    }

    const start = new Date(slotId);
    if (start.getTime() < Date.now()) {
      return res.status(400).json({ error: 'This slot is in the past and cannot be booked.' });
    }
    const end = new Date(start.getTime() + eventType.durationMinutes * 60 * 1000);

    const createdAt = new Date().toISOString();
    const insert = db.prepare(`
      INSERT INTO bookings (event_type_id, start_time, end_time, name, email, created_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `);
    const overlapCheck = db.prepare(`
      SELECT 1 FROM bookings WHERE start_time < ? AND end_time > ? LIMIT 1
    `);

    try {
      const outcome = db.transaction(() => {
        if (overlapCheck.get(end.toISOString(), slotId)) {
          return { conflict: true };
        }
        return { result: insert.run(eventType.id, slotId, end.toISOString(), cleanName, cleanEmail, createdAt) };
      })();

      if (outcome.conflict) {
        return res.status(409).json({ error: 'This time slot is already reserved.' });
      }

      const booking = {
        id: String(outcome.result.lastInsertRowid),
        eventTypeId: String(eventType.id),
        slotId,
        start: slotId,
        end: end.toISOString(),
        name: cleanName,
        email: cleanEmail,
        createdAt,
      };
      return res.status(201).json(booking);
    } catch (err) {
      if (err.code === 'SQLITE_CONSTRAINT_UNIQUE') {
        return res.status(409).json({ error: 'This time slot is already reserved.' });
      }
      throw err;
    }
  });

  router.get('/', (req, res) => {
    const rows = db
      .prepare(`
        SELECT id, event_type_id, start_time, end_time, name, email, created_at
        FROM bookings
        WHERE start_time >= ?
        ORDER BY start_time ASC
      `)
      .all(new Date().toISOString());

    const bookings = rows.map((row) => ({
      id: String(row.id),
      eventTypeId: String(row.event_type_id),
      slotId: row.start_time,
      start: row.start_time,
      end: row.end_time,
      name: row.name,
      email: row.email,
      createdAt: row.created_at,
    }));

    res.json(bookings);
  });

  return router;
}
