import { Router } from 'express';
import { getEventType } from '../event-types.js';
import { generateSlotsForEventType, isValidDateString } from '../slots.js';

// Logic generated by AI Agent: availability lookup. Slots are generated for the
// 14-day booking window, flagged `booked` when an existing booking overlaps
// their interval (across all event types), and past slots are filtered out.
export function slotsRouter(db) {
  const router = Router();

  router.get('/', (req, res) => {
    const { eventTypeId, date } = req.query;

    if (typeof eventTypeId !== 'string' || !/^\d+$/.test(eventTypeId)) {
      return res.status(400).json({ error: 'eventTypeId is required and must be a numeric id.' });
    }

    const eventType = getEventType(db, eventTypeId);
    if (!eventType) {
      return res.status(404).json({ error: 'Event type not found.' });
    }
    if (date !== undefined && !isValidDateString(date)) {
      return res.status(400).json({ error: 'The date parameter must be a valid calendar date in YYYY-MM-DD format.' });
    }

    const booked = db.prepare('SELECT start_time, end_time FROM bookings').all();

    let slots = generateSlotsForEventType(eventType, { booked });
    if (date !== undefined) {
      slots = slots.filter((slot) => slot.date === date);
    }

    const nowIso = new Date().toISOString();
    slots = slots.filter((slot) => slot.start >= nowIso);

    const body = { eventTypeId: String(eventType.id), slots };
    if (date !== undefined) {
      body.date = date;
    }
    res.json(body);
  });

  return router;
}
