export const SLOT_GRID_MINUTES = 30;
export const BUSINESS_START_HOUR = 9;
export const BUSINESS_END_HOUR = 18;
export const BOOKING_WINDOW_DAYS = 14;

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const SLOT_ID_RE = /^(\d{4}-\d{2}-\d{2})T(\d{2}):(\d{2}):00\.000Z$/;

// Logic generated by AI Agent: timezone-free, deterministic slot generation.
// The booking window covers BOOKING_WINDOW_DAYS days starting today (UTC).
// Slots start on a 30-minute grid and must fit entirely inside business hours;
// a slot's end is derived from its event type duration.

export function isValidDateString(date) {
  if (typeof date !== 'string' || !DATE_RE.test(date)) {
    return false;
  }
  const [year, month, day] = date.split('-').map(Number);
  const parsed = new Date(Date.UTC(year, month - 1, day));
  return (
    parsed.getUTCFullYear() === year &&
    parsed.getUTCMonth() === month - 1 &&
    parsed.getUTCDate() === day
  );
}

export function toUtcDateString(date) {
  return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-${String(
    date.getUTCDate(),
  ).padStart(2, '0')}`;
}

export function windowStartUtc(now = new Date()) {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

export function dateInWindow(dateStr) {
  if (!isValidDateString(dateStr)) {
    return false;
  }
  const start = windowStartUtc();
  const end = new Date(start.getTime() + BOOKING_WINDOW_DAYS * 24 * 60 * 60 * 1000);
  const day = new Date(`${dateStr}T00:00:00.000Z`);
  return day >= start && day < end;
}

function overlaps(startIso, endIso, intervals) {
  return intervals.some(([start, end]) => start < endIso && end > startIso);
}

export function generateSlotsForEventType(eventType, { booked = [] } = {}) {
  const intervals = booked.map((b) => [b.start_time, b.end_time]);
  const window = windowStartUtc();
  const slots = [];

  for (let day = 0; day < BOOKING_WINDOW_DAYS; day += 1) {
    const dayStart = new Date(window.getTime() + day * 24 * 60 * 60 * 1000);
    const dateStr = toUtcDateString(dayStart);

    for (let hour = BUSINESS_START_HOUR; hour < BUSINESS_END_HOUR; hour += 1) {
      for (const minute of [0, 30]) {
        const start = new Date(
          Date.UTC(dayStart.getUTCFullYear(), dayStart.getUTCMonth(), dayStart.getUTCDate(), hour, minute, 0),
        );
        const end = new Date(start.getTime() + eventType.durationMinutes * 60 * 1000);
        const dayEnd = new Date(
          Date.UTC(dayStart.getUTCFullYear(), dayStart.getUTCMonth(), dayStart.getUTCDate(), BUSINESS_END_HOUR, 0, 0),
        );

        if (end.getTime() > dayEnd.getTime()) {
          continue;
        }

        const startIso = start.toISOString();
        const endIso = end.toISOString();

        slots.push({
          id: startIso,
          eventTypeId: String(eventType.id),
          date: dateStr,
          start: startIso,
          end: endIso,
          status: overlaps(startIso, endIso, intervals) ? 'booked' : 'available',
        });
      }
    }
  }

  return slots;
}

// Parses a slotId into its date part, or null when malformed.
export function parseSlotId(slotId) {
  if (typeof slotId !== 'string') {
    return null;
  }
  const match = SLOT_ID_RE.exec(slotId);
  if (!match) {
    return null;
  }
  const [, date] = match;
  if (!isValidDateString(date)) {
    return null;
  }
  return { date };
}

// A slot id matches the schedule when its interval (start + event type duration)
// fits entirely within business hours and starts on the 30-minute grid.
export function fitsBusinessHours(eventType, slotId) {
  const start = new Date(slotId);
  const hour = start.getUTCHours();
  const minute = start.getUTCMinutes();
  if (hour < BUSINESS_START_HOUR || hour >= BUSINESS_END_HOUR) {
    return false;
  }
  if (minute !== 0 && minute !== SLOT_GRID_MINUTES) {
    return false;
  }

  const end = new Date(start.getTime() + eventType.durationMinutes * 60 * 1000);
  const dayEnd = new Date(
    Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate(), BUSINESS_END_HOUR, 0, 0),
  );
  return end.getTime() <= dayEnd.getTime();
}
