import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Clock, Globe, Lock, Video } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { listSlots, type EventType, type Owner, type Slot } from '../api';
import { formatTime, timezone } from '../lib/format';
import { cn } from '../lib/utils';
import BookingDialog from './BookingDialog';

const DAY_LABELS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
const WEEKDAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

interface Day {
  date: string;
  weekday: number; // 0 = Sun .. 6 = Sat
  number: number;
  daySlots: Slot[];
}

interface BookingPageProps {
  eventType: EventType;
  owner: Owner;
  onBack: () => void;
}

export default function BookingPage({ eventType, owner, onBack }: BookingPageProps) {
  const [windowSlots, setWindowSlots] = useState<Slot[]>([]);
  const [dayData, setDayData] = useState<{ date: string; slots: Slot[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadingDay, setLoadingDay] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [bookingSlot, setBookingSlot] = useState<Slot | null>(null);

  // Logic generated by AI Agent: sequence counters so a slow response for a
  // previously selected day can never overwrite the current one.
  const windowSeqRef = useRef(0);
  const daySeqRef = useRef(0);

  // Full booking-window load — builds the calendar grid.
  const loadWindow = useCallback(async () => {
    const seq = (windowSeqRef.current += 1);
    setLoading(true);
    try {
      const data = await listSlots(eventType.id);
      if (seq !== windowSeqRef.current) return;
      setWindowSlots(data.slots);
      setError(null);
    } catch (err) {
      if (seq !== windowSeqRef.current) return;
      setError(err instanceof Error ? err.message : 'Something went wrong.');
    } finally {
      if (seq === windowSeqRef.current) setLoading(false);
    }
  }, [eventType.id]);

  // Bug fix (B1): selecting a day refetches GET /api/slots?date=… so the time
  // list always reflects the server's current availability for that date.
  const loadDay = useCallback(
    async (date: string) => {
      const seq = (daySeqRef.current += 1);
      setLoadingDay(true);
      try {
        const data = await listSlots(eventType.id, date);
        if (seq !== daySeqRef.current) return;
        setDayData({ date, slots: data.slots });
        setError(null);
      } catch (err) {
        if (seq !== daySeqRef.current) return;
        setError(err instanceof Error ? err.message : 'Something went wrong.');
      } finally {
        if (seq === daySeqRef.current) setLoadingDay(false);
      }
    },
    [eventType.id],
  );

  useEffect(() => {
    void loadWindow();
  }, [loadWindow]);

  useEffect(() => {
    if (selectedDate) void loadDay(selectedDate);
  }, [loadDay, selectedDate]);

  // Group by the server-provided UTC calendar key (`slot.date`) instead of the
  // browser-local date, so day cells line up exactly with the API's `date`
  // filter in every timezone.
  const days = useMemo<Day[]>(() => {
    const byDate = new Map<string, Slot[]>();
    for (const slot of windowSlots) {
      const list = byDate.get(slot.date) ?? [];
      list.push(slot);
      byDate.set(slot.date, list);
    }
    return [...byDate.entries()]
      .map(([date, slotsForDay]) => {
        const d = new Date(`${date}T00:00:00`);
        return {
          date,
          weekday: d.getDay(),
          number: d.getDate(),
          daySlots: [...slotsForDay].sort((a, b) => a.start.localeCompare(b.start)),
        };
      })
      .sort((a, b) => a.date.localeCompare(b.date));
  }, [windowSlots]);

  // UTC calendar date — matches the keys used by the day grid above.
  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const selected = days.find((d) => d.date === selectedDate) ?? null;

  useEffect(() => {
    if (!loading && !selected && days.length > 0) {
      setSelectedDate(days[0].date);
    }
  }, [days, loading, selected]);

  // Slots shown for the selected day come from the authoritative ?date=
  // fetch once it arrives; until then fall back to the overview snapshot so
  // the list renders instantly.
  const selectedSlots = useMemo(() => {
    if (!selected) return [];
    if (dayData && dayData.date === selected.date) return dayData.slots;
    return selected.daySlots;
  }, [dayData, selected]);

  const grid = useMemo(() => {
    if (days.length === 0) return [];
    const leadingEmpty = (days[0].weekday + 6) % 7; // Monday-based offset
    const cells: ({ empty: true; key: string } | { empty?: false; day: Day; key: string })[] = [];
    for (let i = 0; i < leadingEmpty; i += 1) cells.push({ empty: true, key: `lead-${i}` });
    for (const day of days) cells.push({ day, key: day.date });
    while (cells.length % 7 !== 0) cells.push({ empty: true, key: `trail-${cells.length}` });
    return cells;
  }, [days]);

  const handleBooked = useCallback(() => {
    setBookingSlot(null);
    void loadWindow();
    if (selectedDate) void loadDay(selectedDate);
  }, [loadDay, loadWindow, selectedDate]);

  return (
    <Card className="w-full rounded-[24px]">
      <CardContent className="p-6 sm:p-8">
        <Button type="button" variant="ghost" className="-ml-2 mb-4 px-2 text-muted-foreground" onClick={onBack}>
          ← All meeting types
        </Button>

        <div className="mb-6 flex flex-col gap-4 pt-2">
          <h1 className="flex flex-wrap items-center gap-2 text-2xl font-bold">
            {owner.name}
            <Badge variant="secondary">{eventType.name}</Badge>
          </h1>
          <div className="flex flex-wrap items-center gap-4 text-sm font-medium text-muted-foreground">
            <span className="inline-flex items-center gap-1.5">
              <Clock className="size-4" /> {eventType.durationMinutes}m
            </span>
            <span className="inline-flex items-center gap-1.5">
              <Video className="size-4" /> Online
            </span>
            <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f0f4f8] px-3 py-1 text-xs font-semibold text-foreground">
              <Globe className="size-3.5" /> {timezone()}
            </span>
          </div>
        </div>

        {error && (
          <Alert variant="destructive" className="mb-4">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        <div className="grid grid-cols-7 gap-1">
          {DAY_LABELS.map((label) => (
            <span key={label} className="pb-2 text-center text-[11px] font-semibold text-muted-foreground/60">
              {label}
            </span>
          ))}
          {grid.map((cell) =>
            cell.empty ? (
              <span key={cell.key} className="invisible py-2 text-center text-sm" />
            ) : (
              <button
                key={cell.key}
                type="button"
                id={`day-${cell.day.date}`}
                onClick={() => setSelectedDate(cell.day.date)}
                aria-pressed={cell.day.date === selected?.date}
                className={cn(
                  'rounded-full border py-2 text-center text-sm font-medium transition-colors',
                  cell.day.date === today
                    ? 'border-transparent bg-foreground font-semibold text-background'
                    : cell.day.date === selected?.date
                      ? 'border-primary text-primary'
                      : 'border-border hover:bg-muted',
                )}
              >
                {cell.day.number}
              </button>
            ),
          )}
        </div>

        <Separator className="my-6" />

        {loading ? (
          <p className="text-muted-foreground">Loading available times…</p>
        ) : !selected ? (
          <p className="text-muted-foreground">No available slots in the next 14 days.</p>
        ) : (
          <div className="flex gap-6">
            <div className="flex w-24 shrink-0 flex-col gap-2 pt-2">
              <span className="text-base font-semibold">{WEEKDAY_NAMES[selected.weekday]}</span>
              <span className="text-5xl font-bold leading-none" data-testid="selected-day-number">
                {String(selected.number).padStart(2, '0')}
              </span>
            </div>
            <div className="flex flex-1 flex-col gap-2">
              {loadingDay ? (
                <p className="text-muted-foreground">Loading available times…</p>
              ) : (
                <>
                  {selectedSlots.map((slot) => {
                    const taken = slot.status === 'booked';
                    return (
                      <button
                        key={slot.id}
                        type="button"
                        data-testid={slot.id}
                        disabled={taken}
                        onClick={() => setBookingSlot(slot)}
                        className={cn(
                          'flex w-full items-center justify-between gap-3 rounded-xl border border-border px-4 py-3.5 text-left transition-colors',
                          taken ? 'cursor-not-allowed bg-muted/40' : 'hover:bg-muted/50',
                        )}
                      >
                        <span className={cn('text-[15px] font-semibold', taken && 'text-muted-foreground/70 line-through')}>
                          {formatTime(slot.start)}
                        </span>
                        <span className="inline-flex items-center gap-2 text-[13px] text-muted-foreground">
                          {taken ? <Lock className="size-3.5" /> : <span className="size-1.5 rounded-full bg-border" />}
                          <span className="rounded-full bg-[#eef2f6] px-2 py-0.5 text-xs font-semibold text-muted-foreground">
                            {eventType.durationMinutes}m
                          </span>
                        </span>
                      </button>
                    );
                  })}
                  {selectedSlots.length === 0 && <p className="text-muted-foreground">No times available on this day.</p>}
                </>
              )}
            </div>
          </div>
        )}
      </CardContent>

      <CardFooter className="justify-center gap-2 border-t py-4 text-sm font-semibold text-muted-foreground">
        <span className="flex size-5 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-[10px] font-bold text-white">
          CB
        </span>
        Call Booking
      </CardFooter>

      <BookingDialog
        slot={bookingSlot}
        eventType={eventType}
        onOpenChange={(open) => {
          if (!open) setBookingSlot(null);
        }}
        onBooked={handleBooked}
      />
    </Card>
  );
}
